site_name: NowDeploy
nav:
    - Home: index.md
    - Configuring Your System: configuring.md
    - Catalog Manager: catalogmgr.md
    - Application Builder: appbuildercm.md
    - Application List: applist.md
theme: readthedocs
markdown_extensions:
  - admonition
  - attr_list
